### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ikreb7** [spotify/ramlfications#159]
Hello, what is the status of this project?

**Comment by AlexandreProenca** [comment]
I guess it was abandoned
![Screen Shot 2019-09-10 at 10 07 59](https://user-images.githubusercontent.com/2229747/64616465-0354b300-d3b3-11e9-8cec-6f65a17e3ca7.png)

**Comment by freddrake** [comment]
@econchick mentioned she was having a difficult time finding time for this at PyCon this year; if you're interested in helping maintain the project, it might be good to drop her a line directly.

**Comment by econchick** [comment]
Please see #162
