### ISSUE TITLE
Switch yaml.safe_load for loading RAML files.

### ISSUE THREAD

**Issue by adamcik** [spotify/ramlfications#26]
`yaml.load` can lead to arbitrary code execution when run against untrusted sources. See http://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML for details. Fix should be as simple as just replacing the `load` calls with `safe_load`.

**Comment by econchick** [comment]
YES thank you - I totally agree and I don't know why this wasn't the case to begin with. Thank you!

**Comment by econchick** [comment]
Addressed in #35 - will be in release 0.1.6
