### ISSUE TITLE
Docs raised errors not updated

### ISSUE THREAD

**Issue by AndreasBackx** [spotify/ramlfications#27]
The methods in `/ramlfications/__init__.py` (and perhaps elsewhere) still speak of `InvalidRamlFileError` which doesn't exist (anymore?). I have only picked up ramlfications today, but could it be that this was changed to `ramlfications.errors.InvalidRAMLError` but was forgotton about in the docs?

Since we're on the topic of errors. The documentation also mentions`ramlfications.raml.RAMLParserError`. Wouldn't it be better to move this to `ramlfications.errors.RAMLParserError`?

**Comment by econchick** [comment]
Ah thanks for letting me know about this - I'll look into this a bit more; docs do tend to lag behind the code, which is definitely something I don't want.
