### ISSUE TITLE
RAML version supported by ramlfications?

### ISSUE THREAD

**Issue by freddrake** [spotify/ramlfications#60]
I don't see where the RAML version supported is mentioned in the documentation.  I can only guess that RAML 0.8 is supported.

The supported version should be documented.

Is there a roadmap for supporting RAML 1.0 once the spec is finalized and available?

**Comment by econchick** [comment]
Hi @freddrake - you're right that 0.8 is only supported for now, and that it should be documented appropriately. Thanks for bringing that to my attention.

Re: 1.0: I have an [issue](https://github.com/spotify/ramlfications/issues/54) already filled to just let people know that it is being worked on, and  RAML 1.0 support will be in the ramlfications' [2.0 release](https://github.com/spotify/ramlfications/milestones/0.2.0%20Release). In terms of a more explicit/detailed roadmap, I have one offline for myself. But I guess I should post it in case folks want to help out or read along :)

**Comment by freddrake** [comment]
Thanks!  Just noticed that issue while sitting in a meeting.

I'll leave this open as a documentation issue.
