### ISSUE TITLE
Rendering RAML as md/html/...

### ISSUE THREAD

**Issue by bkabrda** [spotify/ramlfications#84]
Hi, I just wanted to ask whether you're planning to add support for rendering RAML to markdown or html or any other markup language to ramlfications - or perhaps if you're planning to create a separate project for that. I would very much like to contribute to such effort (if not, I guess I'll just create it myself :)).

**Comment by econchick** [comment]
Hey @bkabrda ! Have you seen my other project, [griffin](https://github.com/spotify/griffin)? It takes RAML files and spits out HTML for some static documentation generation.  It's *super* alpha, and it's based on an outdated version of `ramlfications`, but as soon as I finish the [0.2.0](https://github.com/spotify/ramlfications/wiki/RAMLfications-v0.2.0-Release) release, I hope to pick up development again.  If you would like to contribute, that'd be awesome. Let me know and I'll sketch out some issues & plans for it (or you can go ahead and try it out, see what you need that's missing from it).

Feel free to hop into our [Spotify FOSS Slack](https://slackin.spotify.com/) channel, #ramlfications, or on [IRC/Freenode](http://webchat.freenode.net/?channels=%23ramlfications&uio=ND10cnVlJjk9dHJ1ZQb4) if you want to chat more. I'm going to go ahead and close this issue.

Cheers!

LR

**Comment by bkabrda** [comment]
Thanks for the info, I'll check out griffin!
